name: Project Tests

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  project-tests:
    environment: "Project_Deployment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Set up Jayvee
        run: "npm i -g @jvalue/jayvee-interpreter@0.4.0"

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python Modules
        working-directory: ./main/project
        run: "pip install -r requirements.txt"

      - name: Save API Key to temp file
        working-directory: 
        run: printf $DEV_ENV_FILE >> ./main/project/hystreet.key
        env:
          DEV_ENV_FILE : ${{secrets.HYSTREET_API_KEY}}

      - name: Run Test Script
        working-directory: ./main/project
        run: "./tests.sh"
